services:
  - type: web
    name: agmarknet-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn APIwebScrapingPopUp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0 